### ISSUE TITLE
Should we also support async API?

### ISSUE THREAD

**Issue by hailg** [facebook/facebook-java-business-sdk#1]
Hi, I think that a lot of Java/Scala developers would love to use this project. So should we support them with an Async API? For example, we can use Retrofit to support Observable API calls (this is just an example, we don't have to use it). 

The main point is this project will mostly be used by some backend projects. And with them I think that providing some Observable or CompletableFuture APIs is really a need. 

I can also help to develop some code. :)

**Comment by JiamingFB** [comment]
Hi hailg, thanks for your suggestion!

I agree that most developers will use some async framework to make the api calls, and it would be a good idea if we can provide sample async implementation. I'll put it on working item list.

The reason why we kept the current SDK to be synchronous is that people have different preferences on async frameworks. It is relatively easy to wrap sync calls into async calls, but could be hard to convert from one async framework to another.

**Comment by xardazz** [comment]
@JiamingFB It would be really nice if you've supported Asynchronous Jobs (for insights for example https://developers.facebook.com/docs/marketing-api/insights/v2.5 )
If you need to get a huge dataset it's a bit inconvinient to use  sync API that is currently provided.

**Comment by kilink** [comment]
@JiamingFB the problem is that the current design precludes patterns like non-blocking IO. Consumers are now forced to use a thread per request if they don't want to block. I would also argue that going from async to sync can be easy. You don't need to make assumptions about what frameworks people will use, but just build a pluggable abstraction that works with sync and async models.

For example, if the IRequestExecutor interface were to instead return Futures/Promises instead of blocking, then all of the other objects can expose their current synchronous APIs simply by blocking on the result of the future. Then consumers can plug in their preferred async framework via a custom IRequestExecutor.

**Comment by anutin544** [comment]
Ok
