### ISSUE TITLE
AdReportRun Broken

### ISSUE THREAD

**Issue by bdiesenhaus** [facebook/facebook-java-business-sdk#165]
The email field was removed from the API for AdReportRuns so the AdReportRun class in the java sdk now throws the following exception when checking on a report status: 

com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#100) Tried accessing nonexisting field (emails) on node type (AdReportRunV2)","type":"OAuthException","code":100,"fbtrace_id":"AHjBEydc3CF"}}

**Comment by jordan-etleap** [comment]
I also just started experiencing this today. Is this a bug or intended change?

**Comment by jordan-etleap** [comment]
Interestingly, I didn't even request the emails field. Here are the request parameters:
URL: https://graph.facebook.com/v2.11/act_[myaccountid]/insights
method: POST
"time_range" -> "{'since':'2016-12-16','until':'2016-12-19'}"
"level" -> "ad"
"breakdowns" -> "gender,age"
"action_breakdowns" -> " size = 1"
"action_attribution_windows" -> " size = 6"
"sort" -> "date_start"
"time_increment" -> "1"
"fields" -> "cost_per_estimated_ad_recallers,reach,adset_name,total_actions,social_spend,cost_per_unique_action_type,place_page_name,social_impressions,objective,frequency,buying_type,call_to_action_clicks,action_values,video_30_sec_watched_actions,canvas_component_avg_pct_view,unique_outbound_clicks,unique_clicks,video_p75_watched_actions,total_unique_actions,cpc,cost_per_unique_inline_link_click,canvas_avg_view_time,social_clicks,campaign_id,inline_link_click_ctr,ctr,cpm,cpp,video_avg_time_watched_actions,cost_per_inline_link_click,video_p95_watched_actions,unique_link_clicks_ctr,date_start,ad_id,cost_per_unique_outbound_click,inline_post_engagement,adset_id,estimated_ad_recallers,actions,cost_per_unique_click,unique_outbound_clicks_ctr,account_currency,website_ctr,inline_link_clicks,video_10_sec_watched_actions,estimated_ad_recall_rate,cost_per_action_type,outbound_clicks_ctr,campaign_name,unique_inline_link_click_ctr,cost_per_inline_post_engagement,unique_actions,social_reach,video_avg_percent_watch"

**Comment by andrewehale** [comment]
I started running into this as well today with a process that has run daily for months. Looks like the email field has been removed (actually that the object the API returns changed from AdReportRun to AdReportRunV2). Calling fetch() on AdReportRun seems to be the culprit because it looks like fetch is loading the emails property which is no longer existing in the response.

Does anyone have documentation on Facebook removing this? 

Also, thoughts for a workaround? Is there a why to fetch a subset of fields or fetch raw data? Looks like grabbing the raw data is not populated pre fetch.

**Comment by jordan-etleap** [comment]
Here's the Facebook bug submission for those interested: https://developers.facebook.com/support/bugs/1778889978862109/

**Comment by zgrannan** [comment]
Workaround (in Scala):

Instead of running `report.fetch()`,
run:
```scala  
new AdReportRun.APIRequestGet(report.getId, context)
    .requestFields(
       List("getFieldAsyncPercentCompletion", "getFieldAsyncStatus").asJava
    ).execute()
```

Converting this to Java syntax should be pretty straightforward.

**Comment by danieljonesorg** [comment]
```
AdReportRun report = new AdAccount(accountId, context)
                        .getInsightsAsync()
```
is failing with .setFields not including emails.

**Comment by jordan-etleap** [comment]
The fix presented by @zgrannan appears to have worked for me. Thanks!

**Comment by danieljonesorg** [comment]
Here is a java version:
`String status = new AdReportRun.APIRequestGet(report.getId(), context)
                                .requestField("async_status")
                                .execute()
                                .getFieldAsyncStatus();`

**Comment by danieljonesorg** [comment]
Here is the workaround in Java:
`String status = new AdReportRun.APIRequestGet(report.getId(), context)
                                .requestField("async_status")
                                .execute()
                                .getFieldAsyncStatus();`

**Comment by shrikantjoshi** [comment]
A better approach might be to avoid using hard-coded "async_status" string with following minor change:
String status = new AdReportRun.APIRequestGet(report.getId(), context)
                            .requestAsyncPercentCompletionField()
                            .requestAsyncStatusField()
                            .execute();

**Comment by jordan-etleap** [comment]
In the bug report, Facebook claims that they have fixed it and things are running correctly now.

**Comment by vicdus** [comment]
`email` field is removed in latest Java SDK. Updating to latest version in maven should fix it.
