### ISSUE TITLE
unique_conversions and cost_per_unique_conversion as fields with Ads Insights API

### ISSUE THREAD

**Issue by jrg091** [facebook/facebook-java-business-sdk#220]
### Which SDK version are you using?
* 3.2.6

### What's the issue?
It's not clear if `unique_conversions` and `cost_per_unique_conversion` are valid fields as they are defined in the SDK but not listed in https://developers.facebook.com/docs/marketing-api/insights/parameters and the API is not returning an error while using them.

### Steps/Sample code to reproduce the issue
Define a `APIRequestGetInsightsAsync` with:
* `action_breakdowns`: `EnumActionBreakdowns.VALUE_ACTION_TYPE`
* `action_attribution_windows`: [`VALUE_1D_CLICK`, `VALUE_7D_CLICK`, `VALUE_28D_CLICK`, `VALUE_1D_VIEW`, `VALUE_7D_VIEW`, `VALUE_28D_VIEW`]
* `fields`: [`adset_name`, `unique_conversions`]

#### Observed Results:
* If the `unique_conversions` or `cost_per_unique_conversion` are included as fields in the request, the progress for the async task remains unchanged (0 percent). This was checked periodically for an hour.
* If these fields are removed, after a few seconds, the async job finishes and we are able to gather the information.

#### Expected Results:

  * If these fields are invalid, an error should be thrown as if we use as a field: `fooBarSomething`
  * If these fields are valid, a progress should be shown while checking the status for the async job after a couple of minutes

**Comment by jrg091** [comment]
The same happens with `place_page_name`

**Comment by ryancwalsh** [comment]
I use PHP instead of Java and am facing the same issue. I think it's not language-specific.

When I visit https://developers.facebook.com/tools/explorer/ and run this: `/v3.2/act_[my ID]/insights?fields=['conversions']`, it works.

But when I change "conversions" to "unique_conversions", I get:
```
 "error": {
    "message": "An unknown error has occurred.",
    "type": "OAuthException",
    "code": 1,
...
```

**Can any of you at Facebook please help?**

I know that Facebook *tracks* unique conversions because I can see them (such as Unique Searches) in https://business.facebook.com/adsmanager/manage/adsets.

**Comment by ryancwalsh** [comment]
This is still a problem! I wish you'd fix the bug or documentation rather than abandoning the issue and marking it as stale.

When I visit https://developers.facebook.com/tools/explorer/ and run this: `/v5.0/act_[my ID]/insights?time_range={"since":"2015-03-01","until":"2019-10-31"}&fields=['conversions']`, it works.

But when I change "conversions" to "unique_conversions", I get:

```
{
"error": {
    "message": "An unknown error has occurred.",
    "type": "OAuthException",
    "code": 1,
    "fbtrace_id": "AItPaqzX48b2DU4oN43-FDP"
  }
}
```
