### ISSUE TITLE
Automatically fetch next page while iterating APINodeList

### ISSUE THREAD

**Issue by bschlenk** [facebook/facebook-java-business-sdk#67]
APINodeList extends ArrayList, it could easily override iterator() and automatically fetch additional pages.

**Comment by JiamingFB** [comment]
Hi @bschlenk ,

Thanks for the suggestion.

For this issue I'm open for discussion about the pros and cons, and I'd also be happy to hear other developers' opinions.

When we developed the initial version, we had definitely thought about auto-fetching because it would make coding easier for these endpoints. But we eventually choose not to do so, because of a few concerns:

1. APINodeList currently extends ArrayList, but auto-fetching will result in discrepancy between size() and the actual size when you do a for loop with auto-fetching. So looks like if we want to add auto-fetching, we might have to use generic Iterator instead of ArrayList.

2. Auto-fetching potentially throws network exceptions or api exceptions, but the iterator interface doesn't allow these exceptions, and therefore we would have to wrap the exceptions into RuntimeException to mitigate this. This makes error handling less transparent and harder to predict.

3. The purpose of API pagination is to prevent a too-long list of objects from breaking APIs or wasting network resources. I personally feel that if we do auto-fetching, it's encouraging people to simply use a for-loop to iterate over all the objects, which is against our best practice.

**Comment by nicolasdalsass** [comment]
Hi,

Since you're on java 8, wouldn't it be a perfect use case to expose a Stream instead of a Collection ?
I second the original demand, having an easy to use iterating mechanism would make library usage a lot easier.

**Comment by bschlenk** [comment]
It could even be an additional method on all the objects. In addition to having .execute() which returns an APINodeList, there could also be a .stream() method which returns a stream object. For example (using the accounts.getCampaigns example from the README):

```java
AdAccount account = new AdAccount(ACCOUNT_ID, context);
account.getCampaigns().requestAllFields().stream()
    .forEach(campaign -> {
        // process a campaign
    });
```

Or to get all campaigns as a list:

```java
AdAccount account = new AdAccount(ACCOUNT_ID, context);
APINodeList<Campaign> campaigns = account.getCampaigns().requestAllFields().stream()
    .collect(Collectors.toList());
```

The problem of streams not allowing checked exceptions to be thrown still remains though.

**Comment by nicolasdalsass** [comment]
About point 2, why not go really functional and make it a Stream of what in scala would be Either[Throwable, T] ? This way, exceptions are nicely preserved, without having the stream throwing.

Of course, there's no official java support for Either, but there's a a handful of resources on the web on how to have an equivalent in java.

Or it could be a code part wrote in scala, but I don't know how much you'd want that (as a code maintainer, I wouldn't mantain small functional scala parts in a java project).

**Comment by bschlenk** [comment]
Ah yes, that's definitely a valid use case. I should rephrase and say that I can think of plenty of situations where I *would* want to iterate over all of the results of a request. I think your case is a good example of where a stream would be very useful. You could `stream().filter(/* client page in clientPages */).findFirst()`.

**Comment by bschlenk** [comment]
@JiamingFB, I'd like to address this issue again. My team is considering using this library to reduce the amount of time it takes us to update our internal client each release cycle. This isn't a blocker per se, but it would certainly help us with productivity while using this library. We have a way to stream requests to Facebook in our internal library and would love it if we didn't have to take any extra time to implement this in yours.
